### ISSUE TITLE
package.json not in the correct format on the README

### ISSUE THREAD

**Issue by jakejscott** [facebookarchive/DEPRECATED-node-wit#1]
```
{
    "dependencies" : {
        "node-wit" : "1.0.0"
    }
}
```

**Comment by Glavin001** [comment]
They should not even have that in the README. It should be:

> To install `node-wit` run:
> 
> ``` bash
> npm install --save node-wit
> ```

**Comment by tielur** [comment]
@Glavin001 :+1:

**Comment by Glavin001** [comment]
I submitted a PR with the appropriate change to README.
